### ISSUE TITLE
no error posted to route

### ISSUE THREAD

**Issue by Gl4di4torRr** [redhat-cop/cert-utils-operator#9]
I just installed the [cert-manager](https://github.com/jetstack/cert-manager) along with the `cert-utils-operator` and received `field is immutable, spec.tls.key: Invalid value:` when the `cert-utils-operator` and was trying to attach the certificate.

I went into the route to see if there was an error message attached to some metadata but my route was left in the same state as before. Basically, this just leaves the operator in a constant state of looking at my route annotation and trying to apply the cert to the route.

**Comment by raffaelespazzoli** [comment]
what version of OCP are you using? one should be definitely able to change the certificate of a route. In fact you can do it from the console I believe.

**Comment by Gl4di4torRr** [comment]
@raffaelespazzoli i was testing on a 3.10 cluster. I can test on a 3.11 if you would like me to.

**Comment by raffaelespazzoli** [comment]
@Gl4di4torRr yes please. I tested this operator with 3.11 and 4.x and never had the issue you are seeing.

**Comment by Gl4di4torRr** [comment]
uh oh...

```

E0610 12:28:20.580852       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
--
  | /home/travis/gopath/src/github.com/redhat-cop/cert-utils-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
  | /home/travis/gopath/src/github.com/redhat-cop/cert-utils-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
  | /home/travis/gopath/src/github.com/redhat-cop/cert-utils-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
  | /home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/asm_amd64.s:522
  | /home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/panic.go:513
  | /home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/panic.go:82
  | /home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/signal_unix.go:390
  | /home/travis/gopath/src/github.com/redhat-cop/cert-utils-operator/pkg/controller/route/route_controller.go:246
  | /home/travis/gopath/src/github.com/redhat-cop/cert-utils-operator/pkg/controller/route/route_controller.go:170
  | /home/travis/gopath/src/github.com/redhat-cop/cert-utils-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215
  | /home/travis/gopath/src/github.com/redhat-cop/cert-utils-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158
  | /home/travis/gopath/src/github.com/redhat-cop/cert-utils-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
  | /home/travis/gopath/src/github.com/redhat-cop/cert-utils-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
  | /home/travis/gopath/src/github.com/redhat-cop/cert-utils-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
  | /home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/asm_amd64.s:1333
  | panic: runtime error: invalid memory address or nil pointer dereference [recovered]
  | panic: runtime error: invalid memory address or nil pointer dereference
  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x10f6f1d]
  | goroutine 443 [running]:
  | github.com/redhat-cop/cert-utils-operator/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
  | /home/travis/gopath/src/github.com/redhat-cop/cert-utils-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x108
  | panic(0x124fae0, 0x20f2f20)
  | /home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/panic.go:513 +0x1b9
  | github.com/redhat-cop/cert-utils-operator/pkg/controller/route.populateRouteWithCertifcates(0xc0014d96c0, 0xc001764f00)
  | /home/travis/gopath/src/github.com/redhat-cop/cert-utils-operator/pkg/controller/route/route_controller.go:246 +0x2d
  | github.com/redhat-cop/cert-utils-operator/pkg/controller/route.(*ReconcileRoute).Reconcile(0xc0006fdd70, 0xc000360700, 0xc, 0xc0003606b4, 0x7, 0x2107000, 0x0, 0x0, 0x0)
  | /home/travis/gopath/src/github.com/redhat-cop/cert-utils-operator/pkg/controller/route/route_controller.go:170 +0x828
  | github.com/redhat-cop/cert-utils-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00046e280, 0x0)
  | /home/travis/gopath/src/github.com/redhat-cop/cert-utils-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215 +0x18f
  | github.com/redhat-cop/cert-utils-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1()
  | /home/travis/gopath/src/github.com/redhat-cop/cert-utils-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158 +0x36
  | github.com/redhat-cop/cert-utils-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0002def90)
  | /home/travis/gopath/src/github.com/redhat-cop/cert-utils-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
  | github.com/redhat-cop/cert-utils-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0002def90, 0x3b9aca00, 0x0, 0x1, 0xc0006d6000)
  | /home/travis/gopath/src/github.com/redhat-cop/cert-utils-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbe
  | github.com/redhat-cop/cert-utils-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0002def90, 0x3b9aca00, 0xc0006d6000)
  | /home/travis/gopath/src/github.com/redhat-cop/cert-utils-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
  | created by github.com/redhat-cop/cert-utils-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
  | /home/travis/gopath/src/github.com/redhat-cop/cert-utils-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157 +0x32a
```

**Comment by raffaelespazzoli** [comment]
@Gl4di4torRr can you give me some context on where/when you saw that error?

**Comment by Gl4di4torRr** [comment]
@raffaelespazzoli i did a dumb thing and created an insecure route LOL. However, this did cause the container to bounce and that shouldn't be the expected behavior. Let me test again and get back to you. Probably won't be today but will get to it ASAP.

**Comment by raffaelespazzoli** [comment]
ok, regardless this is a bug as the code should treat this situation more gracefully.
I will stick to my original design that a route must be already secured. I will filter out events regarding insecure reputes and improve the docs around this aspect.
